# Generated by Django 3.2.20 on 2024-06-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_albummodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TrackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(max_length=200)),
                ('singers', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(max_length=200)),
                ('creaded_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.albummodel')),
            ],
        ),
    ]
