# Generated by Django 3.2.20 on 2024-06-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240614_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='duration',
            field=models.CharField(max_length=200),
        ),
    ]
