# Generated by Django 3.2.20 on 2024-06-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_trackmodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in-progress', 'in-progress'), ('completed', 'completed')], default='completed', max_length=200),
        ),
    ]
