# Generated by Django 3.2.20 on 2024-06-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reviewmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
